app_deployment:
  appName: expense-tracker-ui
  image: nexus-docker-craigmiller160.ddns.net/expense-tracker-ui:latest
  ports:
    - containerPort: 443
  commonProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS
  secure_ingress:
    name: expense-tracker-ingress
    backendIsHttps: true
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /(expense-tracker(/.*)?)
            serviceName: expense-tracker-ui
            portNumber: 443