#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.pnpm/@craigmiller160+js-config@1.0.3_@relmify+jest-fp-ts@2.1.1_@testing-library+dom@9.3.3_@types+n_43echcsgz46czumr5igt6jxmky/node_modules/lint-staged/bin/lint-staged.js --config ./node_modules/@craigmiller160/js-config/configs/lintstaged/.lintstagedrc